### ISSUE TITLE
add methods for constructing an object directly from an `AbstractDict`

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/StructTypes.jl#11]
Sometimes I'll have some big dict which I read in in JSON3, and I can't really specify that only some of the elements should be read in as some specific type.  I then instead wind up with some nested dicts which have the proper form to be construct into some `struct` or whatever, but now they are just Julia `AbstractDict`, and I don't think I have any easy methods to use from `StructTypes` to get it into the actual struct I want any more.

It would therefore be nice to have something like
```julia
construct(dict::AbstractDict, T)
```
analogous to
```julia
JSON3.read(str::AbstractString, T)
```
Which just builds a struct of type `T` for me from a dict (likewise from vectors and whatever else).

**Comment by quinnj** [comment]
Implemented in #28
