### ISSUE TITLE
is `StructTypes.isempty` part of the public API?

### ISSUE THREAD

**Issue by ericphanson** [JuliaData/StructTypes.jl#15]
I'd like to pirate
```julia
StructTypes.isempty(::Missing) = true
```
but it would be good to know if that's an internal method (and so I should pin the version instead of relying on semver). I suspect the answer is yes by default since it's not documented or exported, so I guess this is also a request that it would be nice to be able to avoid writing fields (with JSON3) which are missing if they show up in `StructTypes.omitempties`.

**Comment by DilumAluthge** [comment]
@quinnj Should we just add `StructTypes.isempty(::Missing) = true` to StructTypes.jl?

**Comment by DilumAluthge** [comment]
@quinnj @ericphanson See https://github.com/JuliaData/StructTypes.jl/pull/18, which adds this to StructTypes.jl:
```julia
StructTypes.isempty(::Missing) = true
```

**Comment by DilumAluthge** [comment]
Or see #21, which lets the user fully control which types are considered to be empty, without any type piracy.
