### ISSUE TITLE
docs link in README is broken

### ISSUE THREAD

**Issue by vtjnash** [JuliaData/StructTypes.jl#2]
at https://github.com/JuliaData/StructTypes.jl/blame/master/README.md#L3

**Comment by quinnj** [comment]
Yeah, I can't quite figure out how to get the docs to build; I seem to be following the Documenter-recommended setup, but my docs job doesn't seem to be running w/ travis. I'm wondering if it somehow has to do w/ being registered or not, but I'm not sure.

**Comment by quinnj** [comment]
Ok, figured it out
