### ISSUE TITLE
`omitempties` returning one-element tuple fails

### ISSUE THREAD

**Issue by dm3** [JuliaData/StructTypes.jl#26]
```
StructTypes.omitempties(::Type{Element}) = (:id)
```

results in

```
ERROR: MethodError: no method matching symbolin(::Symbol, ::Symbol)
Closest candidates are:
  symbolin(::Tuple{Vararg{Symbol,N} where N}, ::Symbol) at /Users/user/.julia/packages/StructTypes/CpLmq/src/StructTypes.jl:534
Stacktrace:
```

zero or 2+ element tuples work fine.

**Comment by DilumAluthge** [comment]
This is not a bug in StructTypes.jl.

Your code does not correctly construct a single element tuple.

For example, this code does not construct a single element tuple:
```julia
foo = (:id)
```

This is how you construct a single element tuple:
```julia
foo = (:id,)
```

**Comment by DilumAluthge** [comment]
From the Julia documentation:
> Notice that a length-1 tuple must be written with a comma, `(1,)`, since `(1)` would just be a parenthesized value. `()` represents the empty (length-0) tuple.

Source: https://docs.julialang.org/en/v1/manual/functions/#Tuples

**Comment by dm3** [comment]
Thanks! That wouldn't be the first time I made this mistake either...
