### ISSUE TITLE
Make NamedTupleType a fully "woven in"  StructType? 

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaData/StructTypes.jl#39]
####   &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;            Distinct Sorts of StructTypes (today)

 |    description      |     StructTypes.Types                        |
 |-------------------|---------------------------------------|
 |                           |                                                          |
 |   collective:         | DictType, ArrayType                         |
 |   elementary:      | StringType, NumberType, BoolType |
 |   nondescript      | NullType                                           |

Dicts accommodate multi-typed keys placed in one-to-one_or_more correspondence with multi-typed values. Often, Dicts are constructed with keys of a single, shared type.  It is commonplace to use Dicts where the values share an abstract type or are of a single shared type.
In general, Dicts are not ordered, although an ordering may be imposed if the keys are ordered.
 
Arrays usually keep some given type of information in each "cell", at each indexable position.  Arrays are ordered by indexed enumeration.  The content may be orderable through the content type's ordering. 

NamedTuples are neither as Dicts nor as Arrays.  Their internal content is structurally ordered -- by ordinal position of each field['s name].  External ordering is not readily available for most NamedTuple schema.  An external order may be defined insofar as the field's types are individually ordered (or orderable by fiat).

NamedTuples share some collective and some elementary aspects. They are collective "in the small" (within an instance) and elementary "in the large" (over many realizations of one schema).  One way 
of processing may emphasize functionalities of a collective focus; another computational approach may emphasize elementhood and functional strengths that accompany each NamedTuple instance.

For me to best support StructTypes and other JuliaData packages that rely on StructTypes, `NamedTupleType` would be included as one of StructType's exported Interface Types.

**Comment by quinnj** [comment]
So I've actually been thinking about this lately and I'm actually inclined to define it as `StructTypes.Struct` since it follows all the same properties (ordered, immutable, etc.).

**Comment by JeffreySarnoff** [comment]
That makes sense to me.  I have been thinking about the nearness of NamedTuples and [immutable] structs too.  While they are not the same, their differences are apart from support for ordered fields that have names and take immutable values.

The way each relates a type with a field when the specific type is not predetermined is one behavioral difference. struct fields may have partially predetermined (constrained) types through parameterization and resolved  _at_ construction. NamedTuple fields may have wholly unpredetermined (unconstrained) types resolved _in_ construction.  NamedTuples with predetermined types are more performant in construction than those without.
