### ISSUE TITLE
missing docstring warning

### ISSUE THREAD

**Issue by rapus95** [JuliaData/StructTypes.jl#54]
https://juliadata.github.io/StructTypes.jl/stable/#StructTypes.OrderedStruct

**Comment by quinnj** [comment]
Thanks for the report! Turns out we don't need that reference in the manual since we're already referencing `StructTypes.Struct`.

**Comment by rapus95** [comment]
sure but shouldn't there at least be a note about it being the same as UnorderedStruct? Especially given that Struct is just defaulting to Unordered right now? So the better way would be to properly document UnorderedStruct and then document Struct as defaulting to UnorderedStruct for compatibility reasons and might change in some major version. So that people learn to use the definitions properly 🙈 Also to remove that ugly build warning/error from the documentation. Because right now that looks unintended. 😅
