### ISSUE TITLE
JSON order validation for "data types"

### ISSUE THREAD

**Issue by tpapp** [JuliaData/StructTypes.jl#6]
I think that leaving key-value order up to the JSON implementation is somewhat brittle and going with the mutable structure is not the right solution.

Instead, it would be better if either

1. the construction would validate that all fields are present and in the right order, eg `JSON3.read("{"val2": 2, "val1": 1, "val3": 3}", CoolType)` would reject,
2. the construction would order the fields (and also validate).

I would make 2. the default, and 1. optional (for speed). String comparisons should be cheap, and for most applications the extra runtime is worth not working with (silently) messed up data.

**Comment by non-Jedi** [comment]
To expand on this, I find myself wanting to deserialize json to an immutable `struct` with fieldnames that are identical to the names of the json fields; I cannot guarantee the order of the json fields. Currently the only way of doing this is to use `DictType` and implement a constructor that accepts a `Dict` (which implies that the json will first be deserialized to a `Dict`). A more efficient way of doing this would be well-appreciated.

**Comment by chris-b1** [comment]
ref to https://github.com/quinnj/JSON3.jl/issues/69 - I hadn't seen this issue

I was playing around with a possible implementation - this `construct` would take tuples of names/values and re-order as needed
```julia
function construct(::Type{T}, names::Tuple{Vararg{Symbol, N}}, vals::Tuple) where {N, T}
    reordered_vals = ntuple(i -> vals[Base.fieldindex(T, names[i])], N)                 
    return T(reordered_vals...)                                                         
end                                                                                     
```

It obviously adds overhead vs direct construction but doesn't seem too bad - unless my timing is allowing for too much constant folding and not measuring the right thing
```
julia> @btime Baz(1,2,3)
  1.199 ns (0 allocations: 0 bytes)
Baz(1, 2, 3)

julia> @btime construct(Baz, (:c, :b, :a), (1, 2, 3))
  17.835 ns (0 allocations: 0 bytes)
Baz(3, 2, 1)
```

**Comment by chris-b1** [comment]
This is probably a fairer benchmark

```julia
julia> @btime Baz($Ref((1, 2, 3))[]...)
  9.509 ns (0 allocations: 0 bytes)
Baz(1, 2, 3)

julia> @btime construct(Baz, $Ref((:c, :b, :a))[], $Ref((1, 2, 3))[])
  189.489 ns (2 allocations: 64 bytes)
Baz(3, 2, 1)
```

**Comment by chris-b1** [comment]
A `@generated` function with a namedtuple, like is used in [`ConstructionBase`](https://github.com/JuliaObjects/ConstructionBase.jl/blob/b5686b755bd3bee29b181b3cb18fe2effa0f10a2/src/ConstructionBase.jl#L46) seems to be a good way to specialize out the overhead

```julia
@generated function construct(::Type{T}, vals::NamedTuple) where {T}    
    args = map(fieldnames(T)) do name                                   
         :(vals.$name)                                                  
    end                                                                 
    return Expr(:block,                                                 
                Expr(:meta, :inline),                                   
                Expr(:call, T, args...))                                
end

julia> @btime construct(Baz, Ref(NamedTuple{(:c, :b, :a)}(1, 2, 3))[])
  9.609 ns (0 allocations: 0 bytes)
Baz(3, 2, 1)
```

**Comment by quinnj** [comment]
Ok, as of StructTypes v1.4 and JSON3 v1.7, the strict order requirement for `Struct` has been lifted (with minimal perf penalty). There is a new `StructTypes.OrderedStruct` that can be used if the fastest perf is still desirable and feasible for a given workflow.
