### ISSUE TITLE
Define `Struct()` as the struct type for `<:Exception`?

### ISSUE THREAD

**Issue by ericphanson** [JuliaData/StructTypes.jl#71]
i.e.
```julia
StructTypes.StructType(::Type{<:Exception}) = StructTypes.Struct()
```
I think that's usually the case? (I'm trying to log exceptions as JSON). (This could be superceded by #61, but if we don't go for that, it might still make sense for exceptions).

**Comment by ericwburden** [comment]
I was able to accomplish this with 

```
StructTypes.StructType(::Type{E}) where {E <: Exception} = StructTypes.Struct()
```

**Comment by quinnj** [comment]
Implemented in https://github.com/JuliaData/StructTypes.jl/pull/70
