### ISSUE TITLE
Allow use of a function/complex object to pick the `subtype` of an `AbstractType`?

### ISSUE THREAD

**Issue by kshyatt** [JuliaData/StructTypes.jl#83]
Suppose I have a situation like this:

```
abstract type MyAbs end

struct A <: MyAbs
    id_field::Tuple{String, Int}
    field_a
end

struct B <: MyAbs
    id_field::Tuple{String, Int}
    field_b
end
```

And I want to dispatch constructing using `id_field[1]`. I think currently this isn't supported by the `NamedTuple` approach of `StructTypes.subtypes` and `StructTypes.subtypekey`, but would it make sense to extend them to support such cases?

**Comment by quinnj** [comment]
Yeah, I think we can make this work. It seems like we would keep `StructTypes.subtypekey` as the same, but we need do allow something like `StructTypes.getsubtype` with a default definition like:
```julia
StructTypes.getsubtype(::Type{T}, val) where {T} = StructTypes.subtypes(T)[Symbol(val)]
```

Then you could overload `StructTypes.getsubtype` however you want to take the `val` of the `subtypekey` we found and you just have to return the right subtype to dispatch to.

**Comment by kshyatt** [comment]
Actually I think all you need to do is define a new struct with `get` and `haskey` and friends -- the `subtypes` doesn't *actually* have to be a `NamedTuple`, it just needs to have the ability to look up values from keys. One could imagine a `SubtypeClosure` or something that ingests some function the user defines to transform raw input -> subtype.

**Comment by quinnj** [comment]
Yeah good point
