### ISSUE TITLE
StructTypes.StructType(::Type{Union{}}) is ambiguous

### ISSUE THREAD

**Issue by mrufsvold** [JuliaData/StructTypes.jl#89]
I was trying to check the `StructTypes.StructType` of the `eltype` of some arrays. However, one empty array's `eltype` was defined as `Union{}` which threw a method ambiguity error on `StructTypes.StructType(::Type{Union{}})`. 

Typing kinda breaks my brain, so I'm not sure if `StructTypes.StructType(::T{}) where T` would solve the problem. I also don't know what struct type to use for something that is more nothing than `nothing`! Maybe this really should throw an error since it doesn't make sense to report the StructType of something that doesn't exist. 

Anyway, just thought I'd lift up the weird edge case for your consideration.

**Comment by quinnj** [comment]
Thanks for the report; a PR is up: https://github.com/JuliaData/StructTypes.jl/pull/91. It doesn't hurt ot define, even though there isn't technically a _value_ in Julia that has type `Union{}`.
